NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_BASE = $(call NLUKI_PATH_BASE,$(NLUKI_TARGET_CLASSIC_SYSROOTS)/$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_BASE,$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_WITH_APPENDED_SYS_PATH = export PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_BASE,$1):$$PATH
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_WITH_PREPENDED_SYS_PATH = export PATH=$$PATH:$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_BASE,$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH = $(NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_FIRSTPASS = $(NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_BASE = $(call NLUKI_LIBRARY_PATH_BASE,$(NLUKI_TARGET_CLASSIC_SYSROOTS)/$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_WITH_NO_SYS_PATH = export LIBRARY_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH = export LIBRARY_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_BASE,$1):$$LIBRARY_PATH; export LD_LIBRARY_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_BASE,$1):$$LD_LIBRARY_PATH
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_WITH_PREPENDED_SYS_PATH = export LIBRARY_PATH=$$LIBRARY_PATH:$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_BASE,$1); export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH = $(NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_FIRSTPASS = $(NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE = $(call NLUKI_CPATH_BASE,$(NLUKI_TARGET_CLASSIC_SYSROOTS)/$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_WITH_NO_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE,$1):$$C_INCLUDE_PATH; export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE,$1):$$CPLUS_INCLUDE_PATH
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_WITH_PREPENDED_SYS_PATH = export C_INCLUDE_PATH=$$C_INCLUDE_PATH:$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$$CPLUS_INCLUDE_PATH:$(call NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH = $(NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_FIRSTPASS = $(NLUKI_AUTO_TARGET_CLASSIC_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH)

include HostClassicSysRootSupport.Shared.mak

NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET = $(NLUKI_BUILDROOT)/target-sysroot-overlay-$1-copy-to-classic-sysroot-$2.stamp
define NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT =
$(call NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2): $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/
	mkdir -p $(NLUKI_TARGET_CLASSIC_SYSROOTS)/$2/
	cp -rsfv $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/* $(NLUKI_TARGET_CLASSIC_SYSROOTS)/$2/
	touch $(call NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2)
endef
define NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_NO_LINK =
$(call NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2): $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/
	mkdir -p $(NLUKI_TARGET_CLASSIC_SYSROOTS)/$2/
	cp -rfv $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/* $(NLUKI_TARGET_CLASSIC_SYSROOTS)/$2/
	touch $(call NLUKI_TARGET_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2)
endef