set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_SYSTEM_PROCESSOR "$ENV{NLUKI_ALTERNATIVE_TARGET_ARCH}")

set(CMAKE_C_COMPILER "$ENV{NLUKI_ALTERNATIVE_TARGET_ARCH}-pc-linux-gcc")
set(CMAKE_CXX_COMPILER "$ENV{NLUKI_ALTERNATIVE_TARGET_ARCH}-pc-linux-g++")

set(CMAKE_SYSROOT "$ENV{NLUKI_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# https://stackoverflow.com/a/9234452
set(ENV{PKG_CONFIG_DIR} "")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig:${CMAKE_SYSROOT}/usr/local/lib/pkgconfig:${CMAKE_SYSROOT}/usr/lib64/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})