NLUKI_AUTO_HOST_SYSROOT_PATH_BASE = $(call NLUKI_LIBRARY_PATH_BASE,$(NLUKI_HOST_SYSROOTS)/$1)
NLUKI_AUTO_HOST_SYSROOT_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_HOST_SYSROOT_PATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_PATH_WITH_APPENDED_SYS_PATH = export PATH=$(call NLUKI_AUTO_HOST_SYSROOT_PATH_BASE,$1):$$PATH
NLUKI_AUTO_HOST_SYSROOT_PATH_WITH_PREPENDED_SYS_PATH = export PATH=$$PATH:$(call NLUKI_AUTO_HOST_SYSROOT_PATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_PATH = $(NLUKI_AUTO_HOST_SYSROOT_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_HOST_SYSROOT_PATH_FIRSTPASS = $(NLUKI_AUTO_HOST_SYSROOT_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_BASE = $(call NLUKI_LIBRARY_PATH_BASE,$(NLUKI_HOST_SYSROOTS)/$1)
NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH = export LIBRARY_PATH=$(call NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_BASE,$1):$$LIBRARY_PATH; export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:$(call NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_WITH_PREPENDED_SYS_PATH = export LIBRARY_PATH=$$LIBRARY_PATH:$(call NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_BASE,$1); export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:$(call NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH = $(NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_FIRSTPASS = $(NLUKI_AUTO_HOST_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_HOST_SYSROOT_CPATH_BASE = $(call NLUKI_CPATH_BASE,$(NLUKI_HOST_SYSROOTS)/$1)
NLUKI_AUTO_HOST_SYSROOT_CPATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_HOST_SYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH = export CPATH=$(call NLUKI_AUTO_HOST_SYSROOT_CPATH_BASE,$1):$$CPATH
NLUKI_AUTO_HOST_SYSROOT_CPATH_WITH_PREPENDED_SYS_PATH = export CPATH=$$CPATH:$(call NLUKI_AUTO_HOST_SYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_HOST_SYSROOT_CPATH = $(NLUKI_AUTO_HOST_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_HOST_SYSROOT_CPATH_FIRSTPASS = $(NLUKI_AUTO_HOST_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH)

NLUKI_STRIP_SYSROOT_OVERLAY = $(NLUKI_AUTO_HOST_SYSROOT_PATH_WITH_NO_SYS_PATH); strip \
							--strip-unneeded $(shell find $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/*.so*) \
							$(shell find $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/*.a) $(shell find $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/* -type f -executable)

define NLUKI_MAKE_SYS_ROOT_HOST =
$(NLUKI_HOST_SYSROOTS)/$1: $(foreach sysroot_overlay,$2,$(NLUKI_HOST_SYSROOT_OVERLAYS)/$(sysroot_overlay)) $3
	rm -rfv $(NLUKI_HOST_SYSROOTS)/$1
	mkdir -p $(NLUKI_HOST_SYSROOTS)/$1
	$(foreach sysroot_overlay,$2,cp -rsfv $(NLUKI_HOST_SYSROOT_OVERLAYS)/$(sysroot_overlay)/* $(NLUKI_HOST_SYSROOTS)/$1
	)
endef

define NLUKI_MAKE_SYS_ROOT_HOST_NO_LINK =
$(NLUKI_HOST_SYSROOTS)/$1: $(foreach sysroot_overlay,$2,$(NLUKI_HOST_SYSROOT_OVERLAYS)/$(sysroot_overlay)) $3 
	rm -rfv $(NLUKI_HOST_SYSROOTS)/$1
	mkdir -p $(NLUKI_HOST_SYSROOTS)/$1
	$(foreach sysroot_overlay,$2,cp -rfv $(NLUKI_HOST_SYSROOT_OVERLAYS)/$(sysroot_overlay)/* $(NLUKI_HOST_SYSROOTS)/$1
	)
endef