include HostClassicSysRootSupport.Shared.mak

NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET = $(NLUKI_HOSTROOT)/host-sysroot-overlay-$1-copy-to-classic-sysroot-$2.stamp
define NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT =
$(call NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2): $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/
	mkdir -p $(NLUKI_HOST_CLASSIC_SYSROOTS)/$2/
	cp -rsfv $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/* $(NLUKI_HOST_CLASSIC_SYSROOTS)/$2/
	touch $(call NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2)
endef
define NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_NO_LINK =
$(call NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2): $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/
	mkdir -p $(NLUKI_HOST_CLASSIC_SYSROOTS)/$2/
	cp -rfv $(NLUKI_HOST_SYSROOT_OVERLAYS)/$1/* $(NLUKI_HOST_CLASSIC_SYSROOTS)/$2/
	touch $(call NLUKI_HOST_SYSROOT_OVERLAY_COPY_TO_CLASSIC_SYSROOT_TARGET,$1,$2)
endef