NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_BASE = $(call NLUKI_PATH_BASE,$(NLUKI_BUILDROOT)/PrimarySysRoot)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_BASE,$1)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_WITH_APPENDED_SYS_PATH = export PATH=$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_BASE,$1):$$PATH
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_WITH_PREPENDED_SYS_PATH = export PATH=$$PATH:$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_BASE,$1)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH = $(NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_FIRSTPASS = $(NLUKI_AUTO_TARGET_PRIMARYSYSROOT_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_BASE = $(call NLUKI_LIBRARY_PATH_BASE,$(NLUKI_BUILDROOT)/PrimarySysRoot)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH = export LIBRARY_PATH=$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_BASE,$1):$$LIBRARY_PATH; export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_WITH_PREPENDED_SYS_PATH = export LIBRARY_PATH=$$LIBRARY_PATH:$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_BASE,$1); export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH = $(NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_FIRSTPASS = $(NLUKI_AUTO_TARGET_PRIMARYSYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_BASE = $(call NLUKI_CPATH_BASE,$(NLUKI_BUILDROOT)/PrimarySysRoot)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_WITH_APPENDED_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_BASE,$1):$$C_INCLUDE_PATH; export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_BASE,$1):$$CPLUS_INCLUDE_PATH
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_WITH_PREPENDED_SYS_PATH = export C_INCLUDE_PATH=$$C_INCLUDE_PATH:$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$$CPLUS_INCLUDE_PATH:$(call NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH = $(NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_FIRSTPASS = $(NLUKI_AUTO_TARGET_PRIMARYSYSROOT_CPATH_WITH_APPENDED_SYS_PATH)

NLUKI_PRIMARYSYSROOT := $(NLUKI_BUILDROOT)/PrimarySysRoot