NLUKI_AUTO_SYSROOT_PATH_BASE = $(call NLUKI_PATH_BASE,$(NLUKI_TARGET_SYSROOTS)/$1)
NLUKI_AUTO_SYSROOT_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_SYSROOT_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_PATH_WITH_APPENDED_SYS_PATH = export PATH=$(call NLUKI_AUTO_SYSROOT_PATH_BASE,$1):$$PATH
NLUKI_AUTO_SYSROOT_PATH_WITH_PREPENDED_SYS_PATH = export PATH=$$PATH:$(call NLUKI_AUTO_SYSROOT_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_PATH = $(NLUKI_AUTO_SYSROOT_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_SYSROOT_PATH_FIRSTPASS = $(NLUKI_AUTO_SYSROOT_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_SYSROOT_LIBRARY_PATH_BASE = $(call NLUKI_LIBRARY_PATH_BASE,$(NLUKI_TARGET_SYSROOTS)/$1)
NLUKI_AUTO_SYSROOT_LIBRARY_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH = export LIBRARY_PATH=$(call NLUKI_AUTO_SYSROOT_LIBRARY_PATH_BASE,$1):$$LIBRARY_PATH
NLUKI_AUTO_SYSROOT_LIBRARY_PATH_WITH_PREPENDED_SYS_PATH = export LIBRARY_PATH=$$LIBRARY_PATH:$(call NLUKI_AUTO_SYSROOT_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_LIBRARY_PATH = $(NLUKI_AUTO_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_SYSROOT_LIBRARY_PATH_FIRSTPASS = $(NLUKI_AUTO_SYSROOT_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_SYSROOT_CPATH_BASE = $(NLUKI_TARGET_SYSROOTS)/$1/lib/gcc/x86_64-pc-linux-gnu/17.0.0/include:$(NLUKI_TARGET_SYSROOTS)/$1/lib/gcc/x86_64-pc-linux-gnu/17.0.0/include-fixed:$(NLUKI_TARGET_SYSROOTS)/$1/include:$(NLUKI_TARGET_SYSROOTS)/$1/usr/include:$(NLUKI_TARGET_SYSROOTS)/$1/usr/lib/klibc/include
NLUKI_AUTO_SYSROOT_CPATH_WITH_NO_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_CPATH_BASE,$1):$$C_INCLUDE_PATH; export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_CPATH_BASE,$1):$$CPLUS_INCLUDE_PATH
NLUKI_AUTO_SYSROOT_CPATH_WITH_PREPENDED_SYS_PATH = export C_INCLUDE_PATH=$$C_INCLUDE_PATH:$(call NLUKI_AUTO_SYSROOT_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$$CPLUS_INCLUDE_PATH:$(call NLUKI_AUTO_SYSROOT_CPATH_BASE,$1)
NLUKI_AUTO_SYSROOT_CPATH = $(NLUKI_AUTO_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_SYSROOT_CPATH_FIRSTPASS = $(NLUKI_AUTO_SYSROOT_CPATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_SYSROOT_OVERLAY_PATH_BASE = $(call NLUKI_PATH_BASE,$(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1)
NLUKI_AUTO_SYSROOT_OVERLAY_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_OVERLAY_PATH_WITH_APPENDED_SYS_PATH = export PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_PATH_BASE,$1):$$PATH
NLUKI_AUTO_SYSROOT_OVERLAY_PATH_WITH_PREPENDED_SYS_PATH = export PATH=$$PATH:$(call NLUKI_AUTO_SYSROOT_OVERLAY_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_OVERLAY_PATH = $(NLUKI_AUTO_SYSROOT_OVERLAY_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_SYSROOT_OVERLAY_PATH_FIRSTPASS = $(NLUKI_AUTO_SYSROOT_OVERLAY_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_BASE = $(call NLUKI_LIBRARY_PATH_BASE,$(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1)
NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_WITH_NO_SYS_PATH = export PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_WITH_APPENDED_SYS_PATH = export LIBRARY_PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_BASE,$1):$$LIBRARY_PATH
NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_WITH_PREPENDED_SYS_PATH = export LIBRARY_PATH=$$LIBRARY_PATH:$(call NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_BASE,$1)
NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH = $(NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_FIRSTPASS = $(NLUKI_AUTO_SYSROOT_OVERLAY_LIBRARY_PATH_WITH_APPENDED_SYS_PATH)

NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE = $(call NLUKI_CPATH_BASE,$(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1)
NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_WITH_NO_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE,$1)
NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_WITH_APPENDED_SYS_PATH = export C_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE,$1):$$C_INCLUDE_PATH; export CPLUS_INCLUDE_PATH=$(call NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE,$1):$$CPLUS_INCLUDE_PATH
NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_WITH_PREPENDED_SYS_PATH = export C_INCLUDE_PATH=$$C_INCLUDE_PATH:$(call NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE,$1); export CPLUS_INCLUDE_PATH=$$CPLUS_INCLUDE_PATH:$(call NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_BASE,$1)
NLUKI_AUTO_SYSROOT_OVERLAY_CPATH = $(NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_WITH_APPENDED_SYS_PATH)
NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_FIRSTPASS = $(NLUKI_AUTO_SYSROOT_OVERLAY_CPATH_WITH_APPENDED_SYS_PATH)

NLUKI_STRIP_SYSROOT_OVERLAY = $(NLUKI_AUTO_SYSROOT_PATH_WITH_NO_SYS_PATH); $(NLUKI_TARGET_ARCH)-pc-linux-strip \
							--strip-unneeded $(shell find $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/*.so*) \
							$(shell find $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/*.a) $(shell find $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$1/* -type f -executable)

define NLUKI_MAKE_SYS_ROOT_TARGET =
$(NLUKI_TARGET_SYSROOTS)/$1: $(foreach sysroot_overlay,$2,$(NLUKI_TARGET_SYSROOT_OVERLAYS)/$(sysroot_overlay)) $(foreach sysroot_overlay,$4,$(NLUKI_HOST_SYSROOT_OVERLAYS)/$(sysroot_overlay)) $3
	rm -rfv $(NLUKI_TARGET_SYSROOTS)/$1
	mkdir -p $(NLUKI_TARGET_SYSROOTS)/$1
	$(foreach additional_host_overlay,$4,cp -rsfv $(NLUKI_HOST_SYSROOT_OVERLAYS)/$(additional_host_overlay)/* $(NLUKI_TARGET_SYSROOTS)/$1
	)
	$(foreach sysroot_overlay,$2,cp -rsfv $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$(sysroot_overlay)/* $(NLUKI_TARGET_SYSROOTS)/$1
	)
endef

define NLUKI_MAKE_SYS_ROOT_TARGET_NO_LINK =
$(NLUKI_TARGET_SYSROOTS)/$1: $(foreach sysroot_overlay,$2,$(NLUKI_TARGET_SYSROOT_OVERLAYS)/$(sysroot_overlay)) $(foreach sysroot_overlay,$4,$(NLUKI_HOST_SYSROOT_OVERLAYS)/$(sysroot_overlay)) $3 
	rm -rfv $(NLUKI_TARGET_SYSROOTS)/$1
	mkdir -p $(NLUKI_TARGET_SYSROOTS)/$1
	$(foreach additional_host_overlay,$4,cp -rfv $(NLUKI_HOST_SYSROOT_OVERLAYS)/$(additional_host_overlay)/* $(NLUKI_TARGET_SYSROOTS)/$1
	)
	$(foreach sysroot_overlay,$2,cp -rfv $(NLUKI_TARGET_SYSROOT_OVERLAYS)/$(sysroot_overlay)/* $(NLUKI_TARGET_SYSROOTS)/$1
	)
endef