name: Makefile CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v6
      with:
        path: Submodules
        key: ${{ runner.os }}-submodules-cache

    - uses: actions/checkout@v7
      name: Recursive Checkout
      with:
        submodules: 'recursive'

    - name: Download GCC Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: cd Submodules/gcc; ./contrib/download_prerequisites
    
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-26.05

    - name: Make Host Tools
      run: nix-shell --pure --run "make -L -j3 nluki-host NLUKI_TARGET_ARCH=${{ matrix.arch }}"

    - name: Make CC Tools
      run: nix-shell --pure --run "make -L -j3 nluki-cc NLUKI_TARGET_ARCH=${{ matrix.arch }}"

    - name: Make
      run: nix-shell --pure --run "make -L -j3 NLUKI_TARGET_ARCH=${{ matrix.arch }}"

    #- name: Run check
      #run: make check

    #- name: Run distcheck
      #run: make distcheck
